services:
  lay-deputy-hub:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/sirius-lay-deputy-hub
    build:
      context: .
      dockerfile: docker/lay-deputy-hub/Dockerfile
      target: prod
    ports:
      - "6666:6666"
    read_only: false
    environment:
      PORT: 6666
      PREFIX: /supervision/deputies/lay
      HEALTHCHECK: /supervision/deputies/lay/health-check
      SIRIUS_PUBLIC_URL: http://localhost:8080
      JWT_SECRET: mysupersecrettestkeythatis128bits

  watch-assets:
    image: node:24-alpine3.23@sha256:244cc2b53f46f9e876304391d17682b0ddae9ac33491f4857e25e35a36ba7995
    working_dir: /home/node/app
    entrypoint: ["sh"]
    volumes:
      - ./web:/app/web
      - ./package.json:/app/package.json

  go-lint:
    image: golangci/golangci-lint:v2.12.2@sha256:5cceeef04e53efe1470638d4b4b4f5ceefd574955ab3941b2d9a68a8c9ad5240
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app
      - ./.cache/golangci-lint/v2.4.0:/root/.cache
    command: golangci-lint run -v --timeout 5m

  test-runner:
    build:
      context: docker/test-runner/
    command: gotestsum --junitfile test-results/unit-tests.xml -- ./... -coverprofile=test-results/test-coverage.txt
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app
      - ./.gocache:/go/pkg/mod
