services:
  lay-deputy-hub:
    build:
      target: dev
    networks:
      - sirius
    ports:
      - "1234:1234"
      - "2345:2345"
    volumes:
      - ./.air.toml:/app/.air.toml
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./main.go:/app/main.go
      - ./internal:/app/internal
      - ./web/static:/app/web/static
      - ./web/template:/app/web/template
    environment:
      SIRIUS_PUBLIC_URL: http://frontend-proxy
      SIRIUS_URL: http://frontend-proxy
      PREFIX: /supervision/deputies/lay

networks:
  sirius:
    name: opg-sirius_default
    external: true